### PR TITLE
Add hex, erlang and brunch icons

### PR DESCRIPTION
**Pull request by joshprice**
Got the erlang icon from http://karlll.github.io/erlang_icon/ if a bigger one is needed.
Brunch came from https://github.com/brunch/brunch/blob/master/lib/logo.png

### CODE REVIEW

**Comment by keithpitt** [comment]
Nice! Could you resize the images to ensure they're 75x75? 😉

**Comment by keithpitt** [comment]
@joshprice poke :)

**Comment by joshprice** [comment]
All icons now 75x75, sorry about the delay

**Comment by keithpitt** [comment]
Nice, thanks!

**Pull request merged**
