### PR TITLE
New emoji for Boomi 

### PR DESCRIPTION
**Pull request by boomiguy**
Boomi iPaaS data platform can now use Buildkite to trigger builds. www.boomi.com

### CODE REVIEW

**Comment by boomiguy** [comment]
Hi when can we expect this PR to be merged?

**Comment by ticky** [comment]
Hi @boomiguy, just out of curiosity, what’s the integration? I can’t seem to find anything on your site about it!

**Comment by boomiguy** [comment]
Boomi is a leading integration iPaaS platform, and Boomi users can leverage Buildkite to create their DevOps pipeline. Read more about this at  https://boomi.com/solutions/initiatives/devops/.

**Comment by jayco** [comment]
@boomiguy thanks for the info and the contribution! 🎉

**Pull request merged**
