### PR TITLE
Update support for Emoji 4.0 (Unicode 9.0)

### PR DESCRIPTION
**Pull request by ticky**
This is preliminary work to take advantage of iamcal/emoji-data#78 when it lands.

Also follows on from #66.

### CODE REVIEW

**Comment by keithpitt** [comment]
Ah ha! Nice! I've been keeping an eye on that pull request for aagggges now, waiting it to drop so we can add all the fresh new emojis!

I think we _may_ need to update how our emoji parser works with modifiers. I built first parser around the concept of just 1 modifier. "thumbs up" + "fitzpatrick skin tone modifier 3" for example. 

But now there are genders and occupations, so in some cases there could be 3 additional modifiers to an original emoji. It _may_ just work, but we'll need to double check!

**Comment by keithpitt** [comment]
I'm also very excited about Buildkite getting the shiny new 🚀 emoji!

**Comment by ticky** [comment]
Yeah, I kinda just wanted to get it integrated somehow so I could see what it’d take to take it all the way!

It’s a shame emoji-data is 900MB or I’d totally consider submoduling it.

**Comment by keithpitt** [comment]
> It’s a shame emoji-data is 900MB or I’d totally consider submoduling it.

Yeah...

**Comment by ticky** [comment]
[Aha!](https://www.npmjs.com/package/emoji-datasource-apple)

**Comment by ticky** [comment]
I’ve done a bit of testing with this, and it feels like a good win.

All the colon codes work just fine.

What _doesn’t_ work out of the box is matching ZWJ sequences (which is already broken, of course!);

`:woman_woman_girl:` is fine, but as `👩‍👩‍👧` still renders as `👩👩👧`. Likewise, `:female-detective::skin-tone-2:` is all good, but `🕵🏻‍♀️` decomposes to `🕵🏻 ‍♀️` - I suspect this’ll be a minor unicode regex change, in the end!

**Comment by ticky** [comment]
We can totally land this in the next few days 😱

**Comment by ticky** [comment]
buildkite/frontend#270 and buildkite/buildkite#2116 have been updated with more robust support for updated Unicode emoji matching

**Pull request merged**
