### PR TITLE
Add karma emoji!

### PR DESCRIPTION
**Pull request by robjacoby**
This is from karma-runner.github.io

### CODE REVIEW

**Comment by keithpitt** [comment]
Nice! Can you also add it to `img-buildkite-64.json`

**Comment by robjacoby** [comment]
Updated - apologies I missed it!

**Comment by keithpitt** [comment]
Ha ha, sorry @robjacoby - can you also add it to the top of the Readme? <3

**Comment by keithpitt** [comment]
:dancers:

**Pull request merged**
