### PR TITLE
add a png

### PR DESCRIPTION
**Pull request by tk0221**
:assurance: 
assurance64

### CODE REVIEW

**Comment by tk0221** [comment]
tyvm

**Comment by jayco** [comment]
Hey @tk0221 thanks for the PR, could you tell us a little more about assurance?

**Comment by tk0221** [comment]
Assurance is a softwarecompany based on Seattle, WA, USA. https://assurance.com/careers
And we also use buildkite. @jayco

**Comment by jayco** [comment]
Thanks for the info and submitting this @tk0221 🎉

**Pull request merged**
