### PR TITLE
Add more elastic emojis for buildkite

### PR DESCRIPTION
**Pull request by liza-mae**
Adding more elastic emojis for use in Buildkite

### CODE REVIEW

**Comment by jfhinchcliffe** [comment]
LGTM! Thanks, @liza-mae

**Comment by liza-mae** [comment]
Thanks @jfhinchcliffe how soon after merging can I use these emojis on buildkite.com?

**Comment by liza-mae** [comment]
I tried now but was it did not recognize it

**Comment by jfhinchcliffe** [comment]
It'll appear in the next few days 👍

**Pull request merged**
