### PR TITLE
Added :tinker:

### PR DESCRIPTION
**Pull request by PhonesMYOB**
Added a logo that I'll be using for a tool at my work

### CODE REVIEW

**Comment by ticky** [comment]
Hi @PhonesMYOB, is this emoji for a tool that is public, or is it just for internal use?

**Comment by PhonesMYOB** [comment]
This tool is for internal use

**Comment by keithpitt** [comment]
@PhonesMYOB mind renaming it to `myob_tinker` in that case? We'll merge it in afterwards :)

**Comment by keithpitt** [comment]
Closed until @PhonesMYOB has time to add the prefix

**Pull request closed without merging**
