### PR TITLE
Add PlatformIO icon

### PR DESCRIPTION
**Pull request by rohansingh**
### Description

Icon for [PlatformIO][1], an IDE and development platform for embedded devices.

[1]: https://platformio.org/

### PR checklist

* [x] The image is 64x64 PNG image
* [x] Image is added to `img-buildkite-64` directory
* [x] Image is referenced in `img-buildkite-64.json` file
* [x] Image is referenced in README markdown file
* [x] The image can be hosted by Buildkite and made available in Buildkite UI

### CODE REVIEW

**Comment by JuanitoFatas** [comment]
Thanks, could you rebase and we’ll merge this in 🙇🏻

**Comment by rohansingh** [comment]
@JuanitoFatas Rebase complete.

**Comment by rohansingh** [comment]
Rebased again, hopefully good now.

**Review by JuanitoFatas — APPROVED** [review]
Awesome, thanks for your contributions!

**Pull request merged**
