### PR TITLE
Add Medical Symbol emoji

### PR DESCRIPTION
**Pull request by hally9k**
Add the following emoji to the buildkite emojis:
`:medical_symbol:`

staff-of-aesculapius

### CODE REVIEW

**Comment by ticky** [comment]
Sorry to say this one is still present but has been renamed in our upstream emoji provider. It’s now `:medical_symbol:`, as of Iamcal/emoji-data#117.

**Comment by hally9k** [comment]
@ticky 😞 
image

**Comment by hally9k** [comment]
I can't find the medical symbol in this repo and it doesn't seem to work so I've updated the naming in this PR and reopened.

**Comment by ticky** [comment]
Ah, on more digging it looks like the reason we don’t have it in our list is because it doesn’t actually render as an emoji on Apple platforms (where our emoji images are from), so it’s been omitted.

**Comment by toolmantim** [comment]
Thanks for working through it with us @hally9k, and taking the time to submit the PR! 🙏🏼😊

**Pull request merged**
