### PR TITLE
Add BitPaket BWS logo

### PR DESCRIPTION
**Pull request by gencer**
This PR add support fot "BitPaket" (BitPaket Web Services aka. BWS). Which belongs to Cloud Apps and Services from Nienbo.

### CODE REVIEW

**Comment by jayco** [comment]
@gencer just out of curiosity, what’s the integration? I can’t seem to find anything on it, looks like the https://www.bitpaket.com link is broken?

**Comment by jayco** [comment]
@gencer I think it would be best to just limit the alias to ': bitpaket:'

**Comment by gencer** [comment]
Hey @jayco BitPaket is a new project and will be out of BETA soon. Currently we have limited access to bitpaket.com and bitpaketbws.com. It has many services in it. From Easy SAtorage Service to Cloud Computing, PostgreSQL as a Service, Key-Calue Database using REST, Secret Management. Similar to AWS.

**Comment by gencer** [comment]
Hey @jayco BitPaket is a new project and will be out of BETA soon. Currently we have limited access to bitpaket.com and bitpaketbws.com. (IP Restrictions except API Endpoints) It has many services in it. From Easy Storage Service to Cloud Computing, PostgreSQL as-a-service, Key-Value Database using REST, Secret Management. You may think BitPaket as similar to AWS.

Sure, I have removed `bws` and `paket` aliases and limit to `bitpaket` only.

image
(As BitPaket, Nienbo main website also has restrictions)

image
image




However, you can access to https://api.bitpaket.com/

**Comment by jayco** [comment]
@gencer Thanks for the extra info and updating the PR, we are happy to revisit this, once it is out of BETA and in use 🙌

**Comment by gencer** [comment]
@jayco Oh. Sad to hear that you cannot accept this PR now :( Emojis looks awesome on Buildktie and I loved being using them. I was goinmg to use this logo everywhere :(

Anyway, It is your call in the end.

**Comment by gencer** [comment]
For now I'll close this as i've removed fork. I'll open when I have more info about discussion we had above. (Shortly, I'll be back)

Thanks!

**Pull request closed without merging**
