### PR TITLE
Add some equinix logos

### LINKED ISSUE #345: Add Equinix emoji
The accompanying PR will add an emoji for Equinix to denote use of Equinix Metal
bare metal services in build pipeilnes.

### PR DESCRIPTION
**Pull request by mmlb**
### Description

Logos for [Equinix](https://www.equinix.com) and [Equinix Metal](https://deploy.equinix.com).  
Closes #345 

### PR checklist

* [x] The image is 64x64 PNG image
* [x] Image is added to `img-buildkite-64` directory
* [x] Image is referenced in `img-buildkite-64.json` file
* [x] Image is referenced in README markdown file
* [x] The image can be hosted by Buildkite and made available in Buildkite UI

### CODE REVIEW

**Comment by himalb001** [comment]
Hi @mmlb, thanks for creating the PR. One of the image doesn't look to be 64x64 png. Once the image is updated, I can merge the changes.

**Comment by mmlb** [comment]
Hey @himalb001 should be updated now, thanks for looking.

**Comment by himalb001** [comment]
@mmlb equinix.png is still coming up as 64x42. A bit of empty space on the top and bottom to make it 64x64 should do it. 

These emojis can be used in a lot of places and having a non-square image may not render as we want in some places.

**Comment by mmlb** [comment]
> @mmlb equinix.png is still coming up as 64x42. A bit of empty space on the top and bottom to make it 64x64 should do it.
> 
> These emojis can be used in a lot of places and having a non-square image may not render as we want in some places.

Ohh :facepalm:!! *Now* it should be updated to actually 64x64.

**Comment by himalb001** [comment]
Awesome! I'll merge this in and it should be available in Buildkite in the next few days! 

Thanks for the contribution

**Review by himalb001 — APPROVED** [review]

**Pull request merged**
