### PR TITLE
Add a Packer emoji

### PR DESCRIPTION
**Pull request by toolmantim**
Before:

before

After:

after

For @lox <3

### CODE REVIEW

**Comment by lox** [comment]
<3

**Comment by toolmantim** [comment]
Turns out there's no vector version of the logo I could find (@captainill might have one?)… had to recreate it :)

hashicorp packer logo

**Comment by keithpitt** [comment]
@toolmantim you cool for me to merge this?

**Comment by toolmantim** [comment]
@keithpitt yep!

**Comment by keithpitt** [comment]
I made some big changes to the Readme, and so it was easier to just copy the emoji to master than figure out the merge conflicts :P (sorry for being lazy). This is now in master!

**Pull request closed without merging**
