### PR TITLE
Add :rollbar:

### PR DESCRIPTION
**Pull request by SomeoneWeird**

### CODE REVIEW

**Comment by sj26** [comment]
Your ideas are intriguing to me and I wish to subscribe to your newsletter

**Comment by keithpitt** [comment]
Looks good! I'll just tweak the logo in master (I'll remove the text so the logo is much larger)

**Comment by SomeoneWeird** [comment]
Sounds good.

**Comment by keithpitt** [comment]
:rocket:'ing to prod now!

**Pull request merged**
