### PR TITLE
Update docker emoji

### PR DESCRIPTION
**Pull request by ngan**
### Description

The Docker logo has changed as per:
https://www.docker.com/company/newsroom/media-resources/

This updates the logo image.

### PR checklist

* [x] The image is 64x64 PNG image
* [x] Image is added to `img-buildkite-64` directory
* [x] Image is referenced in `img-buildkite-64.json` file
* [x] Image is referenced in README markdown file
* [x] The image can be hosted by Buildkite and made available in Buildkite UI

### CODE REVIEW

**Comment by moskyb** [comment]
g'day @ngan! this looks allgood to me. unfortunately there's a merge conflict - would you be able to rebase with main to resolve it?

that said, i don't know how you'd rebase with images in the diffs.... happy for you to recreate this PR if necessary. set me as the reviewer and i'll ✅ it asap

**Comment by JuanitoFatas** [comment]
Ah sorry, monday morning and I messed up with the rebase I wanted to do for @ngan, I’ll reopen this.

**Comment by ngan** [comment]
@JuanitoFatas thanks! I wanted to note a few things:

The png I put up was not 65x65...It's actually 65x46. Not sure if that's ok or not. I don't have an image editor to resize the canvas to 65x65. If it absolutely has to be that size then I'll have to find something to do that for me 🤣.

I noticed a lot of the other emojis are 75x75. Is that just legacy?

**Comment by JuanitoFatas** [comment]
> The png I put up was not 65x65...It's actually 65x46. Not sure if that's ok or not. I don't have an image editor to resize the canvas to 65x65. If it absolutely has to be that size then I'll have to find something to do that for me 🤣.

Haha I also tried to get it to `64x64`, but the image from docker official itself is not a square... We display it as a small image `14x14` on the pipeline, so it should be fine.


> I noticed a lot of the other emojis are 75x75. Is that just legacy?

Ohhh good catch 😍, I’ll create a ticket internally to resize them to `64x64` where possible 👍🏻 

Thanks for raising this @ngan 🙇🏻

**Comment by JuanitoFatas** [comment]
@ngan [updated as 64x64 in the end](https://github.com/buildkite/emojis/pull/508#issuecomment-1742243462), thanks again for updating the docker emoji! Much appreciated <3

**Pull request closed without merging**
