### PR TITLE
Update docker emoji

### PR DESCRIPTION
**Pull request by JuanitoFatas**
I accidentally wanted to help with rebase but closed the original #507 and cannot push to ngan’s remote, so reopened a PR here that is adding updated docker emoji rebased on latest main.

---

### Description

The Docker logo has changed as per:
https://www.docker.com/company/newsroom/media-resources/

This updates the logo image.

### PR checklist

* [x] The image is 64x64 PNG image
* [x] Image is added to `img-buildkite-64` directory
* [x] Image is referenced in `img-buildkite-64.json` file
* [x] Image is referenced in README markdown file
* [x] The image can be hosted by Buildkite and made available in Buildkite UI

### CODE REVIEW

**Comment by JuanitoFatas** [comment]
Actually the image is not matching their guideline

CleanShot 2023-10-02 at 08 49 17@2x

let me adjust the image.

**Review by moskyb — APPROVED** [review]
tysm @JuanitoFatas and @ngan!!

**Comment by ngan** [comment]
Hey @JuanitoFatas considering that these are tiny tiny icons, it would be great if the image could be taken to the edge so that it's as big as it can be. Regarding their guidelines, they overlook for small icons like their favicon:

https://www.docker.com/wp-content/uploads/2023/04/cropped-Docker-favicon-32x32.png

Wdyt?

**Comment by moskyb** [comment]
sounds like a good idea to me.

**Pull request merged**
