### PR TITLE
Add auditjs

### PR DESCRIPTION
**Pull request by calvinbui**
Image from https://github.com/sonatype-nexus-community/auditjs/blob/master/assets/images/auditjs.png

### CODE REVIEW

**Review by chloeruka — APPROVED** [review]
This one looks good too, I just fixed up some brackets. Cheers!

**Comment by calvinbui** [comment]
actually i fixed the brackets that someone else misaligned

now they're misaligned again

**Comment by chloeruka** [comment]
🤦‍♀️ ahh I see, I'll fix that up

**Comment by calvinbui** [comment]
@chloeruka how/when does Buildkite pick up the new emojis?

image

**Comment by calvinbui** [comment]
Seems to appear now

**Pull request merged**
