### PR TITLE
Emoji: YAML

### PR DESCRIPTION
**Pull request by jufemaiz**
- Added the :yaml: emoji
- Fixed the :pylint: emoji (removed aliases)

### CODE REVIEW

**Comment by keithpitt** [comment]
Thanks for the changes! I wonder what that YAML logo will look like on a black background (like the build log). Maybe it won't matter? Do they have alternative logos that don't have black in them?

**Comment by jufemaiz** [comment]
Hmmm good point.

The alternative that YAML had was worse on a black background. Ref: https://github.com/yaml/yaml-spec/blob/master/logo.png

I went with the yaml.io option instead. Ref: https://github.com/yaml/www.yaml.io/blob/master/img/logo-2x.png

Could always put it on a flat white background?

**Comment by ticky** [comment]
In cases that there isn’t already one, I tend to go in and add a stroke to vendors’ icons manually. I just did pytest in this way!

**Comment by jufemaiz** [comment]
Sounds good @ticky! I've applied a stroke.

**Pull request merged**
