### PR TITLE
Add svelte emoji

### PR DESCRIPTION
**Pull request by joekrump**
### Description

Adds the Svelte emoji
https://svelte.dev/

### PR checklist

* [x] The image is 64x64 PNG image
* [x] Image is added to `img-buildkite-64` directory
* [x] Image is referenced in `img-buildkite-64.json` file
* [x] Image is referenced in README markdown file
* [x] The image can be hosted by Buildkite and made available in Buildkite UI

### CODE REVIEW

**Review by jfhinchcliffe — APPROVED** [review]
Thanks @joekrump - LGTM! This'll be available on Buildkite shortly ✨

**Comment by joekrump** [comment]
👋🏻 hey @jfhinchcliffe I'm wondering if something isn't quite right since I'm not seeing the `:svelte:` emoji show up yet. How long does it typically take? Is there something I can check to see if the change is live? 

Here's what I have in my config and here's where I see `:svelte:` in the name of my step still

image

Screenshot 2024-09-09 at 11 10 40 AM

**Comment by jfhinchcliffe** [comment]
Morning @joekrump ! We merge emoji changes in periodically - usually takes a few days.
I've just deployed the main app so now you should see the svelte emoji available now 😁

**Comment by joekrump** [comment]
> Morning @joekrump ! We merge emoji changes in periodically - usually takes a few days. I've just deployed the main app so now you should see the svelte emoji available now 😁

Thanks @jfhinchcliffe . Cheers! Seeing it now:
image

**Pull request merged**
