### PR TITLE
Add :pie: emoji

### PR DESCRIPTION
**Pull request by samjarrett**
Adds the [pie](https://emojipedia.org/pie/) emoji. 🥧 🥧 🥧

### CODE REVIEW

**Comment by ticky** [comment]
Given this is a Unicode emoji, this should be pulled in via an update to our upstream emoji source, rather than added individually as an image. For what it’s worth, you can use any Unicode emoji anywhere already, just not using the name like this :)

**Comment by samjarrett** [comment]
@ticky I asked this in our slack w/ the BK team and got told to submit a PR.

**Comment by keithpitt** [comment]
My apologies @samjarrett ! I though pie was custom, so I was like "sure, submit a PR"! @ticky is our resident expert in this department, so we'll need to do as she suggested.

**Comment by ticky** [comment]
🥧 (as `:pie:`), along with the rest of Unicode 10, is now supported 😃

**Comment by samjarrett** [comment]
Thanks @ticky!

**Comment by ticky** [comment]
No problem! Enjoy the 🥧!

**Pull request closed without merging**
