### PR TITLE
Add vi (vim) hand signal emoji

### PR DESCRIPTION
**Pull request by smbache**
- [x] Add png
- [x] Update json file

vi

### CODE REVIEW

**Comment by ticky** [comment]
Hi @smbache, out of mostly personal curiosity I’d love to know where this one is from and what you plan to use it for! 😄

Also, would you mind adding it to the table in the README in your pull request? 😊

**Comment by smbache** [comment]
Hi @ticky - sure! 😄 It's a mashup tribute to vim, which originates from vi. What can't you use it for? It's vim!

**Comment by ticky** [comment]
I know what vim and vi are, I’m more just curious where this image came from (reverse image search yields nothing but other emoji - is this your own work?) and what your plan is for it in Buildkite?

**Comment by smbache** [comment]
Yeah yeah I made it from a combination of other emojis. It's mostly because we like it here - no specific use different from smiling faces 😄

**Comment by keithpitt** [comment]
@smbache thanks for the submission!

I think you may have inadvertently created a emoji of an offensive hand gesture! (I won't mention it's colloquial name, but it's quite rude and not really SFW).

Being a vim user of 13+ years, I totally support adding a :vi: and :vim: emoji though! Perhaps something like this would be better? If you PR it up, we'll get it accepted in a jiffy :) https://emoji-best.cyder.jp/emoji/396

**Comment by smbache** [comment]
Right, we can't have that. I'm no hand gesture expert :) Thanks for that.

**Pull request closed without merging**
