### PR TITLE
Add emoji for Applied Intuition

### PR DESCRIPTION
**Pull request by yousefhindy**

### CODE REVIEW

**Review by sren-applied — APPROVED** [review]

**Comment by jfhinchcliffe** [comment]
Thanks for the contribution, @yousefhindy 😁
Per the [guidelines](https://github.com/buildkite/emojis#contributing-new-emoji), could you please change the image to a 64x64 px PNG and then we should be good to merge!

**Comment by yousefhindy** [comment]
@jfhinchcliffe done! thanks

**Comment by jfhinchcliffe** [comment]
Ugh, sorry @yousefhindy , someone snuck in a commit and we have some conflicts! Could you please rebase your work and I'll get it in.

**Comment by yousefhindy** [comment]
@jfhinchcliffe should be good now!

**Review by jfhinchcliffe — APPROVED** [review]

**Comment by jfhinchcliffe** [comment]
Thanks for that @yousefhindy ! You'll see this on Buildkite in a few days 🕺

**Pull request merged**
