### PR TITLE
Update emoji-datasource-apple to v15 [FDN-3082]

### PR DESCRIPTION
**Pull request by yob**
I noticed that the [npm package we use as a source for official unicode emojis has been updated with v15 emojis](https://www.npmjs.com/package/emoji-datasource). [v15 includes things like](https://emojipedia.org/emoji-15.0) :black_bird:, :moose:, :jellyfish:, and :pea_pod:. Important additions for use on Buildkite!

Once this is available on buildkite.com, I expect these step labels names would be emojified:

I followed the docs in `docs/updating-unicode.md` but found they needed to be tweaked slightly for current yarn versions.

I also notice that one of the rake tasks updated `all_emoji_names.txt` with the new emojis, but also a range of recently added custom emojis. Are we supposed to update the file when merging custom emoji PRs? 🤷‍♂️

This is similar to the v14 update in #369, and the v7 update in #330.

### CODE REVIEW

**Review by sj26 — APPROVED** [review]
Looks right to me!

Did you try updating the submodule in buildkite/buildkite, too, to make sure it's working end-to-end?

**Comment by yob** [comment]
> Did you try updating the submodule in buildkite/buildkite, too, to make sure it's working end-to-end?

I did not. I assumed (unwisely?) that this follows the typical format for adding emojis so it'd be fine 😅

**Comment by sj26** [comment]
Only asking because of the yarn changes .. but I don’t think they’ll have any impact, so probably just ignore me!

**Review by JuanitoFatas — APPROVED** [review]
👍🏻

**Pull request merged**
