### PR TITLE
Add batman logo

### PR DESCRIPTION
**Pull request by agouz**

### CODE REVIEW

**Comment by toolmantim** [comment]
Hi @agouz — thanks for the contribution! Is this related to any dev tool or service? I did a Google, but couldn't find any. We mostly only accept dev tool-related emojis sorry.

**Comment by agouz** [comment]
No it is not, it's batman dude :)

I found partyparrot in the list of emojis so I thought why not :)

Thanks anyway, worth a shot.

**Comment by toolmantim** [comment]
Argh, and this is your first GitHub pull request! Let me check with the team and see ☺️

**Comment by toolmantim** [comment]
@agouz let's do it! Batman is joining the ranks of Buildkite emojis. And congratulations on your first pull request! 🎉

**Comment by agouz** [comment]
Made my day...
Buildkite is now officially my favourite to CICD platform :)

**Pull request merged**
