### PR TITLE
Add a Chrome icon

### PR DESCRIPTION
**Pull request by jamesottaway**
I generated `chrome.png` from the `app.icns` file in my local `Google Chrome.app`.

### CODE REVIEW

**Comment by keithpitt** [comment]
Nice, thanks!

**Comment by keithpitt** [comment]
screen shot 2016-09-21 at 10 54 04 am

**Comment by jamesottaway** [comment]
Did this go away?

builds_ _warp_gate

**Comment by ticky** [comment]
maaaaybe just briefly 😅

screen shot 2016-09-28 at 6 36 36 pm

**Pull request merged**
