### PR TITLE
Adds Jenkins emoji

### PR DESCRIPTION
**Pull request by nwmiller**

### CODE REVIEW

**Comment by toolmantim** [comment]
Thanks @nwmiller! Any chance you could increase the size of the image, so that it goes all the way to the edges?

**Comment by nwmiller** [comment]
> Thanks @nwmiller! Any chance you could increase the size of the image, so that it goes all the way to the edges?

Should be all set now!

**Comment by toolmantim** [comment]
Thanks @nwmiller, and sorry for the delay! I tried to push up a non-stretched version to your pull request, but I don't believe you've allowed that.

Here's an updated image:

jenkins

Could you replace the image with that, and I can merge it?

**Comment by nwmiller** [comment]
@toolmantim 

Thanks for the corrected image! Updated in my PR.

**Pull request merged**
