### PR TITLE
Add icon of Prometheus

### PR DESCRIPTION
**Pull request by ericsyh**
Provide the emoji icon of Prometheus

### CODE REVIEW

**Comment by ticky** [comment]
Hi @ericsyh! This will just need adding to https://github.com/buildkite/emojis/blob/master/img-buildkite-64.json 😃

**Comment by ericsyh** [comment]
@ticky Thx! I remove the change in README file and PTAL again.

**Comment by ticky** [comment]
Sorry, I should’ve been clearer, it needs to be in both the JSON and readme, it was just missing in the json! ☺️

**Comment by ericsyh** [comment]
I see. Just update in readme file.

**Comment by ticky** [comment]
Thanks @ericsyh!

**Pull request merged**
