### PR TITLE
:sparkles: Add Backstage logo to emojis

### PR DESCRIPTION
**Pull request by mcncl**
Don't want to be using a ◀️ 🎤  combination any more, it's time to dedicate an emoji to Backstage.

### CODE REVIEW

**Review by nosammai — APPROVED** [review]
🥇

**Review by jessicavilaysak — APPROVED** [review]
🥳

**Comment by jfhinchcliffe** [comment]
Thanks for this @mcncl !
Logo size looks good but could you turn off your auto-formatting so we don't have a 4.2k line diff and we'll be ready to merge :)

**Comment by mcncl** [comment]
@jfhinchcliffe sorry about that, prettier did a number on me there. Diff is now +7, which seems nicer. 😄

**Comment by jfhinchcliffe** [comment]
Cheers @mcncl ! It'll be available on Buildkite in a few days 🙌

**Pull request merged**
