### PR TITLE
Add Looker logo

### PR DESCRIPTION
**Pull request by jordondornbos**

### CODE REVIEW

**Comment by keithpitt** [comment]
Hey @jordondornbos - thanks for the Emoji submission! I've not heard of Looker, what does it do? :)

**Comment by jordondornbos** [comment]
Hey @keithpitt - Looker is a data analytics platform you can hook up to your database (https://looker.com/product). It's a more user-friendly interface to query data and they have a lot of really nice visualization components as well.

**Comment by keithpitt** [comment]
It looks like they have a square version of the logo which may work a bit better for an emoji? 
screen shot 2016-10-10 at 9 48 11 am

**Comment by jordondornbos** [comment]
@keithpitt I browsed around a bit and found this: https://github.com/looker/looker-slackbot/blob/master/looker-bot-icon-512.png. It's the icon they use for their Slack bot. 

I switched it out to be that one.

**Comment by keithpitt** [comment]
screen shot 2016-10-13 at 11 17 51 am

Shipped! Thanks @jordondornbos :)

**Pull request merged**
